### ISSUE TITLE
Cfn-lint 0.24.1 fails to parse paths with special characters

### ISSUE THREAD

**Issue by GeorgeArgyros** [aws-cloudformation/cfn-lint#1242]
*cfn-lint version: *
cfn-lint 0.24.1

*Description of issue.*
Cfn-lint fails to correctly parse paths with special characters such as [] and throws an unhandled exception while executing. For example (file contents do not matter): 

```
$ cfn-lint error\[package-1.1\]foo/cli-strings.yml
Traceback (most recent call last):
  File "/home/user/.local/bin/cfn-lint", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/cfnlint/__main__.py", line 28, in main
    (args, filenames, formatter) = cfnlint.core.get_args_filenames(sys.argv[1:])
  File "/home/user/.local/lib/python3.6/site-packages/cfnlint/core.py", line 146, in get_args_filenames
    if not config.templates:
  File "/home/user/.local/lib/python3.6/site-packages/cfnlint/config.py", line 538, in templates
    add_filenames = glob.glob(filename, recursive=True)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/glob.py", line 55, in _iglob
    yield from _glob1(dirname, basename, dironly)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/rootdir/env/envImprovement/python3.6/lib/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range e-1 at position 16
```

**Comment by kddejong** [comment]
@GeorgeArgyros I came back around to this.  

We use python GLOB to expand paths when looking at directories.  Unfortunately glob also uses `[]` for that expansion.  To escape you are going to have to do something like this.  Not ideal but it will work.

cfn-lint "error[[]package-1.1[]]foo/cli-strings.yaml"
