### ISSUE TITLE
cfn-lint crashes when seeing !!ImportValue

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/cfn-lint#1281]
*cfn-lint version: cfn-lint 0.26.2*

*Description of issue.*

cfn-lint running in VSCode crashed when I accidentally typed: `!!ImportValue somestring` (note the extra exclamation mark).

Crash log:

```Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 10, in <module>
    sys.exit(main())

  File "/usr/local/lib/python2.7/site-packages/cfnlint/__main__.py", line 30, in main
    matches_output = formatter.print_matches(matches)
  File "/usr/local/lib/python2.7/site-packages/cfnlint/formatters/__init__.py", line 87, in print_matches
    sort_keys=True, separators=(',', ': '))
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 443, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 443, in _iterencode
    for chunk in _iterencode(o, _current_indent_level):
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode

    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict

    for chunk in chunks:
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode

    o = _default(o)

  File "/usr/local/lib/python2.7/site-packages/cfnlint/formatters/__init__.py", line 81, in default

    return {'__{}__'.format(o.__class__.__name__): o.__dict__}
AttributeError: '_yaml.Mark' object has no attribute '__dict__'

child process exited with code 1 and signal null
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/ian/.vscode/extensions/kddejong.vscode-cfn-lint-0.10.2/server/out/server.js:167:28)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)```

**Comment by kddejong** [comment]
Thanks for reporting this.  Trying to find the logic that would have resulted in this issue.
A quick add of `!!ImportValue somestring` results in this for me.   Tried in both Python 2.7 and 3.6 got the same results.  The logs you provided definitely point to an issue just need to figure out why one of our Mark are being passed in as a replacement to a Match. 

```
E0000 could not determine a constructor for the tag 'tag:yaml.org,2002:ImportValue'
  in "<unicode string>", line 9, column 16:
          KeyName: !!ImportValue "somestring"
```

**Comment by kddejong** [comment]
Haven't been able to replicate this still.  Lot has changed so I'm going to close this and we can re-open if we get more details.
