### ISSUE TITLE
FileNotFoundError: '05_pricing_property_values.json' resource not found in 'cfnlint.data.ExtendedSpecs.me-central-1'

### ISSUE THREAD

**Issue by galluccicamden** [aws-cloudformation/cfn-lint#2358]
*cfn-lint version: cfn-lint-0.64.0*

*Description of issue.*

When running `pip install --upgrade cfn-lint`, then `cfn-lint --update-specs`, the following error occurs:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\resources.py", line 97, in open_binary
    return open(full_path, mode='rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\\\Documents\\my-repo\\05_pricing_property_values.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\cfnlint\maintenance.py", line 70, in update_resource_spec
    spec = patch_spec(spec, region)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\cfnlint\maintenance.py", line 205, in patch_spec
    all_patches = jsonpatch.JsonPatch(cfnlint.helpers.load_resource(
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\cfnlint\helpers.py", line 335, in load_resource
    return json.loads(pkg_resources.read_text(package, filename, encoding='utf-8'))
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\resources.py", line 139, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\resources.py", line 121, in open_text
    open_binary(package, resource), encoding=encoding, errors=errors)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\resources.py", line 111, in open_binary
    raise FileNotFoundError(message)
FileNotFoundError: '05_pricing_property_values.json' resource not found in 'cfnlint.data.ExtendedSpecs.me-central-1'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\Scripts\cfn-lint.exe\__main__.py", line 7, in <module>
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\cfnlint\__main__.py", line 26, in main
    (args, filenames, formatter) = cfnlint.core.get_args_filenames(sys.argv[1:])
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\cfnlint\core.py", line 152, in get_args_filenames
    cfnlint.maintenance.update_resource_specs()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\cfnlint\maintenance.py", line 42, in update_resource_specs
    pool.starmap(update_resource_spec, pool_tuple)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
FileNotFoundError: '05_pricing_property_values.json' resource not found in 'cfnlint.data.ExtendedSpecs.me-central-1'
```

I have replicated this error in two separate environments.

**Comment by kddejong** [comment]
Publishing a fix for it now.  This shouldn't be a problem currently unless you are removing the files from `src/cfnlint/data/DownloadsMetadata/*.json` and forcing an update of the specs.
