### ISSUE TITLE
Error running cfn-lint -u in docker container

### ISSUE THREAD

**Issue by codycole-wk** [aws-cloudformation/cfn-lint#2451]
### CloudFormation Lint Version

0.68.1

### What operating system are you using?

Mac

### Describe the bug

Running cfn-lint -u is returning an error on the self.map_async function

```
Step 1/10 : FROM python:3-alpine as test
 ---> 5f9e8f452a5c
Step 2/10 : WORKDIR /build/
 ---> Using cache
 ---> 815544dd9bff
Step 3/10 : RUN pip install cfn-lint
 ---> Using cache
 ---> 58d9546b0bec
Step 4/10 : RUN cfn-lint -u
 ---> Running in 98577dc5f17c
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cfnlint/maintenance.py", line 72, in update_resource_spec
    spec = patch_spec(spec, 'all')
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cfnlint/maintenance.py", line 254, in patch_spec
    cfnlint.helpers.load_resource(
  File "/usr/local/lib/python3.11/site-packages/cfnlint/helpers.py", line 346, in load_resource
    return json.loads(pkg_resources.read_text(package, filename, encoding='utf-8'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/resources/_legacy.py", line 18, in wrapper
    warnings.warn(
DeprecationWarning: read_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cfnlint/__main__.py", line 38, in main
    (args, filenames, formatter) = cfnlint.core.get_args_filenames(sys.argv[1:])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cfnlint/core.py", line 195, in get_args_filenames
    cfnlint.maintenance.update_resource_specs(config.force)
  File "/usr/local/lib/python3.11/site-packages/cfnlint/maintenance.py", line 40, in update_resource_specs
    pool.starmap(update_resource_spec, pool_tuple)
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
DeprecationWarning: read_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
```

### Expected behavior

Expected to run successfully to run the cfn-lint on template. 

### Reproduction template

Failing before getting to template

**Comment by codycole-wk** [comment]
This was related to not using Python 3.9
