### ISSUE TITLE
update-spec broken

### ISSUE THREAD

**Issue by Systemgeek-louis** [aws-cloudformation/cfn-lint#2588]
### CloudFormation Lint Version

0.72.8

### What operating system are you using?

Macos 13.1

### Describe the bug

When I tried to run cfn-lint --update-specs I got the error KeyError: 'AWS::WAFv2::RuleGroup.Allow' continuously.  Now when ever I run cfn-lint anything I get this:

 ❰lbohm❙~/Downloads❱✘≻ cfn-lint -v
Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 5, in <module>
    from cfnlint.__main__ import main
  File "/usr/local/lib/python3.10/site-packages/cfnlint/__init__.py", line 7, in <module>
    import cfnlint.conditions
  File "/usr/local/lib/python3.10/site-packages/cfnlint/conditions.py", line 10, in <module>
    import cfnlint.helpers
  File "/usr/local/lib/python3.10/site-packages/cfnlint/helpers.py", line 464, in <module>
    initialize_specs()
  File "/usr/local/lib/python3.10/site-packages/cfnlint/helpers.py", line 461, in initialize_specs
    RESOURCE_SPECS[region] = load_region(region)
  File "/usr/local/lib/python3.10/site-packages/cfnlint/helpers.py", line 455, in load_region
    spec[section][key] = RESOURCE_SPECS["us-east-1"][section][key]
KeyError: 'AWS::WAFv2::RuleGroup.Allow'

### Expected behavior

show me the version

### Reproduction template

Do not have a template to give you.

**Comment by kddejong** [comment]
I'll be taking a look into this shortly.

**Comment by Systemgeek-louis** [comment]
I ended up removing via brew remove and then installing via pip install and was able to install 0.73.1 just fine.  I have not tried to update the specs and will avoid that if I can.

Louis

**Comment by kddejong** [comment]
I'll still look into it. Sometimes the specs we get aren't valid and need to be fixed so I want to track down the issue to make sure everything is okay.

**Comment by kddejong** [comment]
Going to close this one.  I'm guessing there are chances where something could get in a bad state.  We have some improvements in v1 that will fix some of this.
