### ISSUE TITLE
Validating AWS::Elasticsearch::Domain throws an error

### ISSUE THREAD

**Issue by remcozigterman** [aws-cloudformation/cfn-lint#2626]
### CloudFormation Lint Version

0.73.0

### What operating system are you using?

Mac

### Describe the bug

While validating an AWS::Elasticsearch::Domain we get the following exception:
```
Exception: Linter error on line 1: Unknown exception while processing rule E3030: Traceback (most recent call last):
  File "/Users/remcozigterman/Projects/Topicus/cloud/aws-sandbox/.venv/lib/python3.8/site-packages/cfnlint/rules/__init__.py", line 320, in run_check
    return check(*args)
  File "/Users/remcozigterman/Projects/Topicus/cloud/aws-sandbox/.venv/lib/python3.8/site-packages/cfnlint/rules/__init__.py", line 44, in wrapper
    results = match_function(self, filename, cfn, *args, **kwargs)
  File "/Users/remcozigterman/Projects/Topicus/cloud/aws-sandbox/.venv/lib/python3.8/site-packages/cfnlint/rules/__init__.py", line 220, in matchall_resource_sub_properties
    return self.match_resource_sub_properties(  # pylint: disable=E1102
  File "/Users/remcozigterman/Projects/Topicus/cloud/aws-sandbox/.venv/lib/python3.8/site-packages/cfnlint/rules/resources/properties/AllowedValue.py", line 95, in match_resource_sub_properties
    matches.extend(self.check(cfn, properties, specs, property_specs, path))
  File "/Users/remcozigterman/Projects/Topicus/cloud/aws-sandbox/.venv/lib/python3.8/site-packages/cfnlint/rules/resources/properties/AllowedValue.py", line 66, in check
    cfn.check_value(
  File "/Users/remcozigterman/Projects/Topicus/cloud/aws-sandbox/.venv/lib/python3.8/site-packages/cfnlint/template.py", line 747, in check_value
    check_value(
  File "/Users/remcozigterman/Projects/Topicus/cloud/aws-sandbox/.venv/lib/python3.8/site-packages/cfnlint/rules/resources/properties/AllowedValue.py", line 35, in check_value
    allowed_value_specs = kwargs.get("value_specs", {}).get("AllowedValues", {})
AttributeError: 'str' object has no attribute 'get'
```
This occurs when validating the ElasticsearchInstanceType element. At the time of validation, our region is eu-west-1. There the element in the file [eu-west-1.json](e https://github.com/aws-cloudformation/cfn-lint/blob/9795da7f473fbfa9de0e0938d7ecf5004b7eaa51/src/cfnlint/data/CloudSpecs/) is marked as CACHED. In the (https://raw.githubusercontent.com/aws-cloudformation/cfn-lint/9795da7f473fbfa9de0e0938d7ecf5004b7eaa51/src/cfnlint/data/CloudSpecs/us-east-1.json) it is an empty object that does not contain 'AllowedValues'. Due to the [change in version 0.73.0 to the [src/cfnlint/helpers.py](https://github.com/aws-cloudformation/cfn-lint/compare/v0.72.10...v0.73.0#diff-16ef113303599029858740766302febb2a2e850021687bafaa06f9fb1acd5a6a) line 455](https://github.com/aws-cloudformation/cfn-lint/compare/v0.72.10...v0.73.0#), this entry is now added as 'CACHED' to the RESOURCE_SPECS. If an attempt is then made to read from the 'AllowedValues' in [AllowedValue.py line 35](https://github.com/aws-cloudformation/cfn-lint/blob/808ebec502081acd1e8e89e9088ce93cf09d679e/src/cfnlint/rules/resources/properties/AllowedValue.py#L35), an exception will be thrown.

### Expected behavior

Not throwing an exception

### Reproduction template

```yaml
---
AWSTemplateFormatVersion: 2010-09-09
Description: ElasticSearch Domain

Parameters:
  Subnet1Id:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /example/landing-zone/vpc/data-subnet-1-id

Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::000000000000:role/administrator'
            Action: 'es:*'
            Resource: '*'
      EBSOptions:
        EBSEnabled: true
        VolumeType: 'gp2'
        VolumeSize: 35
      DomainName: 'sandbox-update-test'
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: 2
        InstanceType: t3.small.elasticsearch
        ZoneAwarenessEnabled: False
      ElasticsearchVersion: '7.9'
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !Ref KmsKeyId
      NodeToNodeEncryptionOptions:
        Enabled: true
      Tags:
        - Key: ProjectName
          Value: application
      VPCOptions:
        SecurityGroupIds:
          - !Ref DomainSecurityGroup
        SubnetIds:
          - !Ref 'Subnet1Id'
    UpdatePolicy:
      EnableVersionUpgrade: true
```

**Comment by kddejong** [comment]
Fixed in `v0.74.3`
