### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by mailjunze** [aws-cloudformation/cfn-lint#3245]
### CloudFormation Lint Version

cfn-lint 0.87.2

### What operating system are you using?

Mac

### Describe the bug

Getting following error 

cfn-lint --cfn_file deploy/test/apply/***.yaml --aws_region eu-central-1
```
% cfn-lint --cfn_file deploy/test/apply/starter-rule.yaml --aws_region eu-central-1
cfn-lint: AWS CloudFormation Linter`
Linting deploy/test/apply/starter-rule.yaml 
Traceback (most recent call last):
  File "/Users/junabab/.local/bin/cfn-lint", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/cfnlint/cli/cli.py", line 12, in main
    errors = linter(cfn_file, custom_ruleset_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/cfnlint/linter.py", line 11, in linter
    errors = __lint_file(file_path, custom_ruleset)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/cfnlint/linter.py", line 25, in __lint_file
    linter = Linter(file_path, lintrules.cloudformation_rules)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/cfnlint/core/BaseYamlLinter.py", line 18, in __init__
    self.file_as_yaml = self.__load_yaml_file(file_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/junabab/Library/Application Support/pipx/venvs/cfnlint/lib/python3.12/site-packages/cfnlint/core/BaseYamlLinter.py", line 24, in __load_yaml_file
    file_contents_yaml = yaml.load(file_contents)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'
```

### Expected behavior

work without the error

### Reproduction template

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InferenceStarterCWRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      RoleName: abc
      Policies:
        - PolicyName: AllowStateMachineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: !Sub arn:aws:states:eu-central-1:${AWS::AccountId}:stateMachine:*
                Action:
                  - states:StartExecution
  EventRule0:

**Comment by kddejong** [comment]
This is this version of cfn-lint https://pypi.org/project/cfnlint/ not this one https://pypi.org/project/cfn-lint/

Make sure to install using one of the methods on our [readme](https://github.com/aws-cloudformation/cfn-lint?tab=readme-ov-file#install).

**Comment by mailjunze** [comment]
Got it thanks
