### ISSUE TITLE
Crash processing Rules section following upgrade from 1.12.2 to 1.12.3

### ISSUE THREAD

**Issue by scarytom** [aws-cloudformation/cfn-lint#3662]
### CloudFormation Lint Version

1.12.3

### What operating system are you using?

Ubuntu

### Describe the bug

Since upgrading from 1.12.2 to 1.12.3 cfn_lint is crashing on one of my templates with `sympy.core.sympify.SympifyError: SympifyError: None`.  I'll attach the stack trace.

This template happens to have a "Rules" section, which I think is the cause.

[trace.txt](https://github.com/user-attachments/files/16887728/trace.txt)

### Expected behavior

not crashing

### Reproduction template

```{
  "AWSTemplateFormatVersion" : "2010-09-09",

  "Parameters": {
    "FooAccountId": {
      "Type" : "String",
      "MinLength" : "12",
      "MaxLength" : "12",
      "AllowedPattern" : "^[0-9]{12}$",
      "ConstraintDescription" : "AWS Account ID must be 12 digits"
    }
  },

  "Rules" : {
    "expectedAccount" : {
      "Assertions" : [ {
        "Assert" :  { "Fn::Equals": [ { "Ref": "FooAccountId" }, { "Ref" : "AWS::AccountId" } ] },
        "AssertDescription" : "The foo account should match the current logged-in account."
      }
      ]
    }
  },

  "Resources" : {
    "Dummy": {
      "Type": "Custom::NullResource",
      "Properties": { "ServiceToken": { "Ref" : "FooAccountId" } }
    }
  }
}```

**Comment by Ali-M-CIANDT** [comment]
I can confirm I'm having the same issues. Commenting out the "rules" section doesnt throw the error.

The error thrown:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/cfn-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/runner.py", line 452, in main
    runner.cli()
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/runner.py", line 443, in cli
    self._cli_output(list(self.run()))
                     ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/runner.py", line 395, in run
    yield from self._validate_filenames(self.config.templates)
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/runner.py", line 299, in _validate_filenames
    yield from self.validate_template(filename, template)  # type: ignore[arg-type] # noqa: E501
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/runner.py", line 321, in validate_template
    runner = TemplateRunner(filename, template, self.config, self.rules)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/runner.py", line 98, in __init__
    self.cfn = Template(filename, template, self.config.regions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/template/template.py", line 78, in __init__
    self.conditions = cfnlint.conditions.Conditions(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/conditions/conditions.py", line 40, in __init__
    self._cnf, self._solver_params = self._build_cnf(list(self._conditions.keys()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/conditions/conditions.py", line 185, in _build_cnf
    cnf.add_prop(rule.build_cnf(equal_vars))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/conditions/_rule.py", line 143, in build_cnf
    return self._assertions.build_cnf(params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/cfnlint/conditions/_rule.py", line 94, in build_cnf
    return And(*assertions)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/sympy/core/operations.py", line 513, in __new__
    _args = frozenset(cls._new_args_filter(args))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/sympy/logic/boolalg.py", line 578, in _new_args_filter
    args = BooleanFunction.binary_check_and_simplify(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/sympy/core/operations.py", line 506, in <genexpr>
    args = (_sympify_(arg) for arg in args)
            ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/sympy/core/sympify.py", line 514, in _sympify
    return sympify(a, strict=True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/cfn-lint/1.12.3/libexec/lib/python3.12/site-packages/sympy/core/sympify.py", line 400, in sympify
    raise SympifyError(a)
sympy.core.sympify.SympifyError: SympifyError: None
```
